appId: "org.consensio.whisper"

name: screen_security
---
# לא לאפשר צילום מסך של שיחות ומסכים

#---------------------------if-----------------------------
- runFlow: # אם המסך נכבה
    when:
      visible:
        id: "com.android.systemui:id/lock_icon_container"
    commands:
        - runFlow: if_screen_off.yaml
- runFlow: # אם חלון התראות מוצג מעל
    when:
      visible:
            text: "Bluetooth"
    commands:
        - runFlow: if_notification_center.yaml
- runFlow: # אם 3 כפתורי ניווט
    when:
      visible:
        id: "com.android.systemui:id/recent_apps"
    commands:
        - runFlow: if_navigation_to_gesture.yaml
- launchApp
- runFlow: # אם סיגנל לא מחובר לחשבון
    when:
      visible:
        id: "org.consensio.whisper:id/welcome_transfer_or_restore"
    commands:
        - runFlow: test_log_in_account_PIN_code.yaml
        - launchApp
- runFlow: # אם סיגנל נעול עם קוד
    when:
      visible:
        id: "com.android.systemui:id/lockPassword"
    commands:
        - runFlow: if_signal_screen_lock.yaml
- runFlow: # אם הממשק לא באנגלית
    when:
      notVisible: "Chats"
    commands:
        - runFlow: if_gui_not_english.yaml
        - launchApp
#--------------------------------------------------------------
- tapOn: "More options"
- tapOn: "Settings"
- tapOn: "Privacy"
- runFlow:
    when:
      notVisible: "Screen security"
    commands:
        - scrollUntilVisible:
            element:
              text: "Screen security" # or any other selector
            direction: DOWN # DOWN|UP|LEFT|RIGHT (optional, default: DOWN)
            timeout: 50000 # (optional, default: 20000) ms
            speed: 30 # 0-100 (optional, default: 40) Scroll speed. Higher values scroll faster.
            visibilityPercentage: 100 # 0-100 (optional, default: 100) Percentage of element visible in viewport
            centerElement: false # true|false (optional, default: false)
- runFlow: # בדיקה חיובית
    when:
      visible:
        id: "org.consensio.whisper:id/switch_widget"
        index: 1
        checked: true
    commands:
        - tapOn: "Block screenshots in the recents list and inside the app"
        - back
        - back
- swipe:
    start: 48%,99%
    end: 48%,94%
    duration: 1948
- assertVisible: "Screenshot"
- swipe:
    start: 81%,46%
    end: 24%,45%
    duration: 500
- tapOn:
    id: "com.android.launcher3:id/action_buttons"
- assertVisible:
    id: "com.android.systemui:id/screenshot_preview"
- launchApp
- tapOn: "More options"
- tapOn: "Settings"
- tapOn: "Privacy"
- runFlow:
    when:
      notVisible: "Screen security"
    commands:
        - scrollUntilVisible:
            element:
              text: "Screen security" # or any other selector
            direction: DOWN # DOWN|UP|LEFT|RIGHT (optional, default: DOWN)
            timeout: 50000 # (optional, default: 20000) ms
            speed: 30 # 0-100 (optional, default: 40) Scroll speed. Higher values scroll faster.
            visibilityPercentage: 100 # 0-100 (optional, default: 100) Percentage of element visible in viewport
            centerElement: false # true|false (optional, default: false)
- runFlow: # בדיקה שלילית
    when:
      notVisible:
        id: "org.consensio.whisper:id/switch_widget"
        index: 1
        checked: true
    commands:
        - tapOn: "Block screenshots in the recents list and inside the app"
        - back
        - back
- swipe:
    start: 48%,99%
    end: 48%,94%
    duration: 1948
- swipe:
    start: 81%,46%
    end: 24%,45%
    duration: 500
- tapOn:
    id: "com.android.launcher3:id/action_screenshot"
- assertNotVisible:
    id: "com.android.systemui:id/screenshot_preview"
- launchApp
- tapOn: "More options"
- tapOn: "Settings"
- tapOn: "Privacy"
- runFlow:
    when:
      notVisible: "Screen security"
    commands:
        - scrollUntilVisible:
            element:
              text: "Screen security" # or any other selector
            direction: DOWN # DOWN|UP|LEFT|RIGHT (optional, default: DOWN)
            timeout: 50000 # (optional, default: 20000) ms
            speed: 30 # 0-100 (optional, default: 40) Scroll speed. Higher values scroll faster.
            visibilityPercentage: 100 # 0-100 (optional, default: 100) Percentage of element visible in viewport
            centerElement: false # true|false (optional, default: false)
- runFlow:
    when:
      visible:
        id: "org.consensio.whisper:id/switch_widget"
        index: 1
        checked: true
    commands:
        - tapOn: "Block screenshots in the recents list and inside the app"
- back
- back